# Generated by Django 4.1.8 on 2023-04-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Golfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("tournament_position", models.PositiveSmallIntegerField(default=0)),
                ("score_to_par", models.SmallIntegerField(default=0)),
                ("rd_one_tee_time", models.TimeField()),
                ("rd_one_strokes", models.SmallIntegerField(default=0)),
                ("rd_two_tee_time", models.TimeField()),
                ("rd_two_strokes", models.SmallIntegerField(default=0)),
                ("rd_three_tee_time", models.TimeField()),
                ("rd_three_strokes", models.SmallIntegerField(default=0)),
                ("rd_four_tee_time", models.TimeField()),
                ("rd_four_strokes", models.SmallIntegerField(default=0)),
            ],
        ),
    ]
