# Generated by Django 4.1.8 on 2023-04-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0003_golfer_tournament_alter_tournament_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfer",
            name="rd_four_tee_time",
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_one_tee_time",
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_three_tee_time",
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_two_tee_time",
            field=models.TimeField(default=None, null=True),
        ),
    ]
