# Generated by Django 4.1.8 on 2023-04-28 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0005_remove_golfer_tournament_tournament_golfers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="golfers",
        ),
        migrations.AddField(
            model_name="golfer",
            name="tournament",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="golf_contest.tournament"
            ),
        ),
    ]
