# Generated by Django 4.2 on 2023-04-30 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0007_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfer",
            name="rd_four_tee_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_one_tee_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_three_tee_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_two_tee_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="tournament",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="golf_contest.tournament"),
        ),
    ]
