# Generated by Django 4.2.1 on 2023-05-08 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0009_team_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="score",
        ),
    ]
