# Generated by Django 4.2.1 on 2023-05-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0010_remove_team_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfer",
            name="tournament_position",
            field=models.CharField(max_length=4),
        ),
    ]
