# Generated by Django 4.2.1 on 2023-05-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0011_alter_golfer_tournament_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfer",
            name="tournament_position",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
