# Generated by Django 4.2.1 on 2023-05-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0013_alter_golfer_score_to_par"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfer",
            name="rd_four_strokes",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_one_strokes",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_three_strokes",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_two_strokes",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
