# Generated by Django 4.2.1 on 2023-05-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0016_alter_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="golfer",
            name="player_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
