# Generated by Django 4.2.1 on 2023-05-16 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0017_golfer_player_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="golfer",
            unique_together={("player_id", "tournament")},
        ),
    ]
