# Generated by Django 4.2.1 on 2023-05-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0018_alter_golfer_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="bonuses",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="place",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="raw_score",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
