# Generated by Django 4.2.1 on 2023-05-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0019_team_bonuses_team_place_team_raw_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="bonuses",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="raw_score",
            field=models.SmallIntegerField(default=0),
        ),
    ]
