# Generated by Django 4.2.1 on 2023-05-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0020_alter_team_bonuses_alter_team_raw_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="tournament_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
