# Generated by Django 4.2.1 on 2023-05-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0022_team_place_tied"),
    ]

    operations = [
        migrations.AddField(
            model_name="golfer",
            name="tournament_position_tied",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_four_strokes",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_one_strokes",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_three_strokes",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_two_strokes",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
