# Generated by Django 4.2.1 on 2023-05-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0024_alter_golfer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="golfer",
            name="score_today",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="golfer",
            name="thru",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
