# Generated by Django 4.2.1 on 2023-05-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0025_golfer_score_today_golfer_thru"),
    ]

    operations = [
        migrations.AddField(
            model_name="golfer",
            name="rd_four_score_to_par",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="golfer",
            name="rd_one_score_to_par",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="golfer",
            name="rd_three_score_to_par",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="golfer",
            name="rd_two_score_to_par",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
