# Generated by Django 4.2.1 on 2023-05-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0026_golfer_rd_four_score_to_par_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="state",
        ),
        migrations.AddField(
            model_name="tournament",
            name="current_round",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tournament",
            name="status",
            field=models.CharField(default="pre", max_length=15),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_four_strokes",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_one_strokes",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_three_strokes",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rd_two_strokes",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="golfer",
            name="thru",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
