# Generated by Django 4.2.1 on 2023-05-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0027_remove_tournament_state_tournament_current_round_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfer",
            name="thru",
            field=models.CharField(default="", max_length=10),
        ),
    ]
