# Generated by Django 4.2.1 on 2023-05-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0029_alter_golfer_thru"),
    ]

    operations = [
        migrations.AddField(
            model_name="golfer",
            name="rounds",
            field=models.JSONField(
                default=[
                    {
                        "1": {"score_to_par": "", "strokes": "", "tee_time": ""},
                        "2": {"score_to_par": "", "strokes": "", "tee_time": ""},
                        "3": {"score_to_par": "", "strokes": "", "tee_time": ""},
                        "4": {"score_to_par": "", "strokes": "", "tee_time": ""},
                    }
                ]
            ),
        ),
    ]
