# Generated by Django 4.2.1 on 2023-05-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0030_golfer_rounds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfer",
            name="rounds",
            field=models.JSONField(
                default=[
                    {
                        "r1": {"score_to_par": "", "strokes": "", "tee_time": ""},
                        "r2": {"score_to_par": "", "strokes": "", "tee_time": ""},
                        "r3": {"score_to_par": "", "strokes": "", "tee_time": ""},
                        "r4": {"score_to_par": "", "strokes": "", "tee_time": ""},
                    }
                ]
            ),
        ),
    ]
