# Generated by Django 4.2.1 on 2023-05-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0031_alter_golfer_rounds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="golfer",
            name="rd_four_score_to_par",
        ),
        migrations.RemoveField(
            model_name="golfer",
            name="rd_four_strokes",
        ),
        migrations.RemoveField(
            model_name="golfer",
            name="rd_four_tee_time",
        ),
        migrations.RemoveField(
            model_name="golfer",
            name="rd_one_score_to_par",
        ),
        migrations.RemoveField(
            model_name="golfer",
            name="rd_one_strokes",
        ),
        migrations.RemoveField(
            model_name="golfer",
            name="rd_one_tee_time",
        ),
        migrations.RemoveField(
            model_name="golfer",
            name="rd_three_score_to_par",
        ),
        migrations.RemoveField(
            model_name="golfer",
            name="rd_three_strokes",
        ),
        migrations.RemoveField(
            model_name="golfer",
            name="rd_three_tee_time",
        ),
        migrations.RemoveField(
            model_name="golfer",
            name="rd_two_score_to_par",
        ),
        migrations.RemoveField(
            model_name="golfer",
            name="rd_two_strokes",
        ),
        migrations.RemoveField(
            model_name="golfer",
            name="rd_two_tee_time",
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rounds",
            field=models.JSONField(
                default={
                    "r1": {"score_to_par": "", "strokes": "", "tee_time": ""},
                    "r2": {"score_to_par": "", "strokes": "", "tee_time": ""},
                    "r3": {"score_to_par": "", "strokes": "", "tee_time": ""},
                    "r4": {"score_to_par": "", "strokes": "", "tee_time": ""},
                }
            ),
        ),
    ]
