# Generated by Django 4.2.1 on 2023-05-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0032_remove_golfer_rd_four_score_to_par_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="golfer",
            name="status",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="golfer",
            name="rounds",
            field=models.JSONField(
                default={
                    "r1": {"score_to_par": None, "strokes": "", "tee_time": ""},
                    "r2": {"score_to_par": None, "strokes": "", "tee_time": ""},
                    "r3": {"score_to_par": None, "strokes": "", "tee_time": ""},
                    "r4": {"score_to_par": None, "strokes": "", "tee_time": ""},
                }
            ),
        ),
    ]
