# Generated by Django 4.2.1 on 2023-05-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf_contest", "0034_rename_thru_golfer_thru_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="golfer",
            name="thru",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
